name: Update Remote Cached Signals

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update-cache:
    runs-on: ubuntu-latest

    steps:
    - name: Wget ping
      run: wget -q -O /dev/null --timeout=120 --tries=3 --waitretry=5 "https://betterlife.wuaze.com/data.php?update=true&token=B3TT3RLIF3_UPDAT3_T0K3N" || true
